export type Contracts = {
  TARGET_ORACLE_ADDRESS: string
  OBSERVED_ORACLE_ADDRESS: string
  TOKEN_ADDRESS: string
  ENGINE_ADDRESS: string
  GOVERNANCE_TOKEN_ADDRESS: string
  OPTIONS_LISTING_ADDRESS: string
  REWARD_POOL_ADDRESS: string
  SAVINGS_POOL_ADDRESS: string
  VIEWER_CALLBACK_ADDRESS: string
  SYNTHETIC_DEX: string
  GOVERNANCE_DEX: string
}

export const contracts: {
  mainnet: Contracts
  florencenet: Contracts
} = {
  mainnet: {
    TARGET_ORACLE_ADDRESS: '',
    OBSERVED_ORACLE_ADDRESS: '',
    TOKEN_ADDRESS: '',
    ENGINE_ADDRESS: '',
    GOVERNANCE_TOKEN_ADDRESS: '',
    OPTIONS_LISTING_ADDRESS: '',
    REWARD_POOL_ADDRESS: '',
    SAVINGS_POOL_ADDRESS: '',
    VIEWER_CALLBACK_ADDRESS: '',
    SYNTHETIC_DEX: '',
    GOVERNANCE_DEX: ''
  },
  florencenet: {
    TARGET_ORACLE_ADDRESS: 'KT1SS7Cobh9gCTtzoeKGm7xAzJbS11rkJJmN',
    OBSERVED_ORACLE_ADDRESS: 'KT1NAsiqgcz7qaTaz27rRahHeqSFY7Z5QLjn',
    TOKEN_ADDRESS: 'KT1E247BoHxqxqxWd3ZqtsyGiAojfXiZgGhn',
    ENGINE_ADDRESS: 'KT1RAbRtsCv4p6zeHmT8Z9JiSLhRRVpKK3Lf',
    GOVERNANCE_TOKEN_ADDRESS: 'KT19dsHPAPuuDGKGXSkCkb6VoW5G1jJRvUFr',
    OPTIONS_LISTING_ADDRESS: 'KT1UsejJh8rU8VFZV48uJCeSTrS5zVbb8rQk',
    REWARD_POOL_ADDRESS: 'KT1CH3SpaJi7QbemEZYu1jVdrv9H5nsotXA2',
    SAVINGS_POOL_ADDRESS: 'KT1Q184SucS9pUdhW2f9zMWxxzoyM6nQ6xqy',
    VIEWER_CALLBACK_ADDRESS: 'KT1NLqgDPbtdvhbR44YWVk8jFZ37v6QBhh6W%set_address',
    SYNTHETIC_DEX: 'KT1JvkUNXuns3dzJEphZUycdRQdyBNQ5hxS9',
    GOVERNANCE_DEX: 'KT1Nm4skBGXimoKXeUAF1mjLihzgqgjuGcSi'
  }
}
