export type Contracts = {
  TARGET_ORACLE_ADDRESS: string
  OBSERVED_ORACLE_ADDRESS: string
  TOKEN_ADDRESS: string
  ENGINE_ADDRESS: string
  GOVERNANCE_TOKEN_ADDRESS: string
  OPTIONS_LISTING_ADDRESS: string
  REWARD_POOL_ADDRESS: string
  SAVINGS_POOL_ADDRESS: string
  VIEWER_CALLBACK_ADDRESS: string
  SYNTHETIC_DEX: string
  GOVERNANCE_DEX: string
}

export const contracts: {
  mainnet: Contracts
  florencenet: Contracts
} = {
  mainnet: {
    TARGET_ORACLE_ADDRESS: '',
    OBSERVED_ORACLE_ADDRESS: '',
    TOKEN_ADDRESS: '',
    ENGINE_ADDRESS: '',
    GOVERNANCE_TOKEN_ADDRESS: '',
    OPTIONS_LISTING_ADDRESS: '',
    REWARD_POOL_ADDRESS: '',
    SAVINGS_POOL_ADDRESS: '',
    VIEWER_CALLBACK_ADDRESS: '',
    SYNTHETIC_DEX: '',
    GOVERNANCE_DEX: ''
  },
  florencenet: {
    TARGET_ORACLE_ADDRESS: 'KT1PoYUpGxThx6tHh5LcUpiqrw4ezVU3WZKx',
    OBSERVED_ORACLE_ADDRESS: 'KT1D2dHja1Fq16oRUiVDGuDE9BFPeSNzwzry',
    TOKEN_ADDRESS: 'KT1WWPRX4i2QZyJArzRbFBGVChuQ2ZKaYbJ8',
    ENGINE_ADDRESS: 'KT1T1UPijbP1LPX8YTEvWVCQ9QfoBdEiaTjH',
    GOVERNANCE_TOKEN_ADDRESS: 'KT1QhrTH7opwd5wjdSq8vK9L7rAfSrX5e2Ed',
    OPTIONS_LISTING_ADDRESS: 'KT1DTZcnMcmLiyvp7Po9uczMCbKuzcorP6JH',
    REWARD_POOL_ADDRESS: 'KT1BkipMc7hRhGV7SvRuDkyG4hQLhHMzaALH',
    SAVINGS_POOL_ADDRESS: 'KT1M5PBmmYa9VDEUdvcbmEXDzRB9JUmB4YeU',
    VIEWER_CALLBACK_ADDRESS: 'KT1NLqgDPbtdvhbR44YWVk8jFZ37v6QBhh6W%set_address',
    SYNTHETIC_DEX: 'KT1LgFBkVsu3YvcmqLovrxGupMi1GH3iWmuC',
    GOVERNANCE_DEX: 'KT1VeaanA3DmGAkeKhENzdXLex9kBYd4LPnn'
  }
}
