export type Contracts = {
  symbol: AssetField
  TARGET_ORACLE_ADDRESS: string
  OBSERVED_ORACLE_ADDRESS: string
  TOKEN_ADDRESS: string
  TOKEN_ID: string
  ENGINE_ADDRESS: string
  ENGINE_TYPE: EngineType
  GOVERNANCE_TOKEN_ADDRESS: string
  OPTIONS_LISTING_ADDRESS: string
  REWARD_POOL_ADDRESS: string
  SAVINGS_POOL_ADDRESS: string
  VIEWER_CALLBACK_ADDRESS: string
  SYNTHETIC_DEX: string
  GOVERNANCE_DEX: string
}

interface Assets {
  mainnet: {
    [key in AssetField]: Contracts
  }
  florencenet: {
    [key in AssetField]: Contracts
  }
  granadanet: {
    [key in AssetField]: Contracts
  }
}

export type AssetField = 'uUSD' | 'uDEFI'

export enum EngineType {
  TRACKER_V1 = 'tracker-v1',
  TRACKER_V2 = 'tracker-v2',
  CHECKER_V1 = 'checker'
}

export const contracts: Assets = {
  mainnet: {
    uUSD: {
      symbol: 'uUSD',
      TARGET_ORACLE_ADDRESS: 'KT1RC22chBZGJtWv82e5pSeyqyBLEyDRqobz',
      OBSERVED_ORACLE_ADDRESS: 'KT1EZmFNuBx76T8CnTrHeYJ2YeAc7wSGKSRi',
      TOKEN_ADDRESS: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
      TOKEN_ID: '0',
      ENGINE_ADDRESS: 'KT1FFE2LC5JpVakVjHm5mM36QVp2p3ZzH4hH',
      ENGINE_TYPE: EngineType.TRACKER_V1,
      GOVERNANCE_TOKEN_ADDRESS: 'KT1Xobej4mc6XgEjDoJoHtTKgbD1ELMvcQuL',
      OPTIONS_LISTING_ADDRESS: 'KT1RkQaK5X84deBAT6sXJ2VLs7zN4pM7Y3si',
      REWARD_POOL_ADDRESS: 'KT1Lz5S39TMHEA7izhQn8Z1mQoddm6v1jTwH',
      SAVINGS_POOL_ADDRESS: 'KT1M8asPmVQhFG6yujzttGonznkghocEkbFk',
      VIEWER_CALLBACK_ADDRESS: 'KT1UAuApZKc1UrbKL27xa5B6XWxUgahLZpnX%set_address',
      SYNTHETIC_DEX: 'KT1EtjRRCBC2exyCRXz8UfV7jz7svnkqi7di',
      GOVERNANCE_DEX: 'KT1PL1YciLdwMbydt21Ax85iZXXyGSrKT2BE'
    },
    uDEFI: {
      symbol: 'uDEFI',
      TARGET_ORACLE_ADDRESS: 'KT1RC22chBZGJtWv82e5pSeyqyBLEyDRqobz',
      OBSERVED_ORACLE_ADDRESS: 'KT1EZmFNuBx76T8CnTrHeYJ2YeAc7wSGKSRi',
      TOKEN_ADDRESS: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
      TOKEN_ID: '1',
      ENGINE_ADDRESS: 'KT1FFE2LC5JpVakVjHm5mM36QVp2p3ZzH4hH',
      ENGINE_TYPE: EngineType.TRACKER_V2,
      GOVERNANCE_TOKEN_ADDRESS: 'KT1Xobej4mc6XgEjDoJoHtTKgbD1ELMvcQuL',
      OPTIONS_LISTING_ADDRESS: 'KT1RkQaK5X84deBAT6sXJ2VLs7zN4pM7Y3si',
      REWARD_POOL_ADDRESS: 'KT1Lz5S39TMHEA7izhQn8Z1mQoddm6v1jTwH',
      SAVINGS_POOL_ADDRESS: 'KT1M8asPmVQhFG6yujzttGonznkghocEkbFk',
      VIEWER_CALLBACK_ADDRESS: 'KT1UAuApZKc1UrbKL27xa5B6XWxUgahLZpnX%set_address',
      SYNTHETIC_DEX: 'KT1EtjRRCBC2exyCRXz8UfV7jz7svnkqi7di',
      GOVERNANCE_DEX: 'KT1PL1YciLdwMbydt21Ax85iZXXyGSrKT2BE'
    }
  },
  florencenet: {
    uUSD: {
      symbol: 'uUSD',
      TARGET_ORACLE_ADDRESS: 'KT1SS7Cobh9gCTtzoeKGm7xAzJbS11rkJJmN',
      OBSERVED_ORACLE_ADDRESS: 'KT1NAsiqgcz7qaTaz27rRahHeqSFY7Z5QLjn',
      TOKEN_ADDRESS: 'KT1E247BoHxqxqxWd3ZqtsyGiAojfXiZgGhn',
      TOKEN_ID: '0',
      ENGINE_ADDRESS: 'KT1RAbRtsCv4p6zeHmT8Z9JiSLhRRVpKK3Lf',
      ENGINE_TYPE: EngineType.TRACKER_V1,
      GOVERNANCE_TOKEN_ADDRESS: 'KT19dsHPAPuuDGKGXSkCkb6VoW5G1jJRvUFr',
      OPTIONS_LISTING_ADDRESS: 'KT1UsejJh8rU8VFZV48uJCeSTrS5zVbb8rQk',
      REWARD_POOL_ADDRESS: 'KT1CH3SpaJi7QbemEZYu1jVdrv9H5nsotXA2',
      SAVINGS_POOL_ADDRESS: 'KT1Q184SucS9pUdhW2f9zMWxxzoyM6nQ6xqy',
      VIEWER_CALLBACK_ADDRESS: 'KT1NLqgDPbtdvhbR44YWVk8jFZ37v6QBhh6W%set_address',
      SYNTHETIC_DEX: 'KT1JvkUNXuns3dzJEphZUycdRQdyBNQ5hxS9',
      GOVERNANCE_DEX: 'KT1Nm4skBGXimoKXeUAF1mjLihzgqgjuGcSi'
    },
    uDEFI: {
      symbol: 'uDEFI',
      TARGET_ORACLE_ADDRESS: 'KT1SS7Cobh9gCTtzoeKGm7xAzJbS11rkJJmN',
      OBSERVED_ORACLE_ADDRESS: 'KT1NAsiqgcz7qaTaz27rRahHeqSFY7Z5QLjn',
      TOKEN_ADDRESS: 'KT1E247BoHxqxqxWd3ZqtsyGiAojfXiZgGhn',
      TOKEN_ID: '1',
      ENGINE_ADDRESS: 'KT1RAbRtsCv4p6zeHmT8Z9JiSLhRRVpKK3Lf',
      ENGINE_TYPE: EngineType.TRACKER_V2,
      GOVERNANCE_TOKEN_ADDRESS: 'KT19dsHPAPuuDGKGXSkCkb6VoW5G1jJRvUFr',
      OPTIONS_LISTING_ADDRESS: 'KT1UsejJh8rU8VFZV48uJCeSTrS5zVbb8rQk',
      REWARD_POOL_ADDRESS: 'KT1CH3SpaJi7QbemEZYu1jVdrv9H5nsotXA2',
      SAVINGS_POOL_ADDRESS: 'KT1Q184SucS9pUdhW2f9zMWxxzoyM6nQ6xqy',
      VIEWER_CALLBACK_ADDRESS: 'KT1NLqgDPbtdvhbR44YWVk8jFZ37v6QBhh6W%set_address',
      SYNTHETIC_DEX: 'KT1JvkUNXuns3dzJEphZUycdRQdyBNQ5hxS9',
      GOVERNANCE_DEX: 'KT1Nm4skBGXimoKXeUAF1mjLihzgqgjuGcSi'
    }
  },
  granadanet: {
    uUSD: {
      symbol: 'uUSD',
      TARGET_ORACLE_ADDRESS: 'KT1KpYtbnf5Cam67mEqQHZ4m3KSYg9rLZoPe',
      OBSERVED_ORACLE_ADDRESS: 'KT1VC9L8wqRQSEF9N5rp7Bv3jfLRGvREdumC',
      TOKEN_ADDRESS: 'KT1L9iniM6swtx95o5SHUiFdG3rWxq8pfpHb',
      TOKEN_ID: '0',
      ENGINE_ADDRESS: 'KT1SgoxzCRKc3ZmsPK4DAxcqPwVhvSLgD9B6',
      ENGINE_TYPE: EngineType.TRACKER_V1,
      GOVERNANCE_TOKEN_ADDRESS: 'KT1JbCE1p9A6fH5aDvmp7qhHEXbtRY6mRibH',
      OPTIONS_LISTING_ADDRESS: 'KT1TT5kCb7QQXAYAhRoRqHgBR1DJyAK28cpg',
      REWARD_POOL_ADDRESS: 'KT1FXftd9mDLbZnc1YxrsX5kePoCxgb7cYHT',
      SAVINGS_POOL_ADDRESS: 'KT1Npj6gJqLejJScFJRoJTsNCYSc4FxAxLZ2',
      VIEWER_CALLBACK_ADDRESS: 'KT1BsxQutEW7tKd1X5KuNAKptMZca9gCdetb%set_address',
      SYNTHETIC_DEX: 'KT1Kc7MrMeN4AgSpD25ZMgFmgMdo1Yqhp8wL',
      GOVERNANCE_DEX: 'KT1Mw43GDjXPT6uJVP9zEjfnQxgWbK55EECe'
    },
    uDEFI: {
      symbol: 'uDEFI',
      TARGET_ORACLE_ADDRESS: 'KT1J4xNE5Y1ajhC1mvNMMVkd2N7FqPCEjrRf',
      OBSERVED_ORACLE_ADDRESS: 'KT1AvaA1496XaangqtnqgZcUtp9VZCwUhkvo',
      TOKEN_ADDRESS: 'KT1L9iniM6swtx95o5SHUiFdG3rWxq8pfpHb',
      TOKEN_ID: '1',
      ENGINE_ADDRESS: 'KT1CLZfC284yLipFbeoH5VuLqPgXJmFaeLnA',
      ENGINE_TYPE: EngineType.TRACKER_V2,
      GOVERNANCE_TOKEN_ADDRESS: 'KT1JbCE1p9A6fH5aDvmp7qhHEXbtRY6mRibH',
      OPTIONS_LISTING_ADDRESS: 'KT1QAUqDbmF7XQsnXup62Q8nbsN8Wss94ygS',
      REWARD_POOL_ADDRESS: 'KT1MfGAdqV48VCx7WPHosWVx6kjzE9tWCE6g',
      SAVINGS_POOL_ADDRESS: 'KT1KG9pt81QcwKZ3Dq7fcMbg4gcumDno2Bmb',
      VIEWER_CALLBACK_ADDRESS: 'KT1BsxQutEW7tKd1X5KuNAKptMZca9gCdetb%set_address',
      SYNTHETIC_DEX: 'KT1SxFN15bT4TtxdJQ5s9TLA9arYE3dk5ay7',
      GOVERNANCE_DEX: 'KT1Mw43GDjXPT6uJVP9zEjfnQxgWbK55EECe'
    }
  }
}
